In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("hr_attrition_dirty.csv")

In [3]:
print(df.head())
print(df.info())
print(df.describe())
print(df.shape)

  EmployeeID    EmployeeName   Age  Gender               Department  \
0    EMP7367   Daniel Garcia   NaN  Female                       IT
1    EMP6604    Daniel Moore  19.0    Male                    R & D
2    EMP4384    Sandra Smith  43.0    Male  Research & Development
3    EMP5511  Michael Harris  27.0    Male                    R & D
4    EMP5299      Mark Davis  22.0    Male                    Sales

                 JobRole    EducationField  Education MonthlyIncome  \
0                    NaN  Technical Degree          5       18140.0
1        Operations Lead             Other          2        3643.0
2        Operations Lead     Life Sciences          2        2507.0
3   Marketing Specialist         Marketing          4        4526.0
4  Laboratory Technician           Medical          5        1637.0

   HourlyRate  ...     BusinessTravel  MaritalStatus  DistanceFromHome  \
0          90  ...         Non-Travel        Married                11
1          30  ...         Non-Travel       divorced                30
2          58  ...      Travel_Rarely        Married                10
3          91  ...         Non-Travel        Married                17
4          99  ...  Travel_Frequently       Divorced                26

   OverTime  PercentSalaryHike  TrainingTimesLastYear  StockOptionLevel  \
0       NaN                 23                      2                 3
1       NaN                 18                      4                 0
2       YES                 15                      6                 0
3        No                 16                      1                 2
4        No                 23                      1                 3

   JobInvolvement  Attrition  JoiningDate
0               1         No  19 Nov 2010
1               3        no     13-7-2019
2               4        Yes          NaN
3               1         No   11/24/2018
4               3         No          NaN

[5 rows x 31 columns]
<class 'pandas.DataFrame'>
RangeIndex: 8300 entries, 0 to 8299
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmployeeID                8300 non-null   str
 1   EmployeeName              8300 non-null   str
 2   Age                       7315 non-null   str
 3   Gender                    8300 non-null   str
 4   Department                7360 non-null   str
 5   JobRole                   7451 non-null   str
 6   EducationField            8300 non-null   str
 7   Education                 8300 non-null   int64
 8   MonthlyIncome             7526 non-null   str
 9   HourlyRate                8300 non-null   int64
 10  DailyRate                 8300 non-null   int64
 11  YearsAtCompany            7708 non-null   float64
 12  YearsInCurrentRole        8300 non-null   int64
 13  YearsWithCurrManager      8300 non-null   int64
 14  TotalWorkingYears         7188 non-null   float64
 15  NumCompaniesWorked        8300 non-null   int64
 16  JobSatisfaction           7308 non-null   float64
 17  EnvironmentSatisfaction   8300 non-null   int64
 18  WorkLifeBalance           7409 non-null   float64
 19  PerformanceRating         7720 non-null   float64
 20  RelationshipSatisfaction  8300 non-null   int64
 21  BusinessTravel            8300 non-null   str
 22  MaritalStatus             8300 non-null   str
 23  DistanceFromHome          8300 non-null   int64
 24  OverTime                  7695 non-null   str
 25  PercentSalaryHike         8300 non-null   int64
 26  TrainingTimesLastYear     8300 non-null   int64
 27  StockOptionLevel          8300 non-null   int64
 28  JobInvolvement            8300 non-null   int64
 29  Attrition                 8300 non-null   str
 30  JoiningDate               6510 non-null   str
dtypes: float64(5), int64(13), str(13)
memory usage: 2.0 MB
None
         Education   HourlyRate    DailyRate  YearsAtCompany  \
count  8300.000000  8300.000000  8300.000000     7708.000000
mean      3.003373    65.236988   749.992530       19.222237
std       1.408917    20.585808   377.768492       40.801345
min       1.000000    30.000000   100.000000       -3.000000
25%       2.000000    47.000000   418.750000        8.000000
50%       3.000000    66.000000   755.000000       17.000000
75%       4.000000    83.000000  1074.250000       26.000000
max       5.000000   100.000000  1400.000000      999.000000

       YearsInCurrentRole  YearsWithCurrManager  TotalWorkingYears  \
count         8300.000000           8300.000000        7188.000000
mean             6.918193              6.594940          19.872148
std              5.347469              5.060428          11.786772
min              0.000000              0.000000           0.000000
25%              2.000000              2.000000          10.000000
50%              6.000000              6.000000          20.000000
75%             11.000000             11.000000          30.000000
max             18.000000             17.000000          40.000000

       NumCompaniesWorked  JobSatisfaction  EnvironmentSatisfaction  \
count         8300.000000      7308.000000              8300.000000
mean             4.474578         2.515599                 2.516627
std              2.869152         1.106559                 1.120992
min              0.000000         1.000000                 1.000000
25%              2.000000         2.000000                 2.000000
50%              4.000000         3.000000                 3.000000
75%              7.000000         4.000000                 4.000000
max              9.000000         4.000000                 4.000000

       WorkLifeBalance  PerformanceRating  RelationshipSatisfaction  \
count      7409.000000        7720.000000               8300.000000
mean          2.505196           3.146373                  2.461566
std           1.121413           0.353503                  1.110409
min           1.000000           3.000000                  1.000000
25%           2.000000           3.000000                  1.000000
50%           3.000000           3.000000                  2.000000
75%           4.000000           3.000000                  3.000000
max           4.000000           4.000000                  4.000000

       DistanceFromHome  PercentSalaryHike  TrainingTimesLastYear  \
count       8300.000000        8300.000000            8300.000000
mean          15.630482          18.053133               2.993253
std            8.662193           4.315483               1.984930
min            1.000000          11.000000               0.000000
25%            8.000000          14.000000               1.000000
50%           16.000000          18.000000               3.000000
75%           23.000000          22.000000               5.000000
max           30.000000          25.000000               6.000000

       StockOptionLevel  JobInvolvement
count       8300.000000     8300.000000
mean           1.488193        2.524699
std            1.116205        1.113292
min            0.000000        1.000000
25%            0.000000        2.000000
50%            1.000000        3.000000
75%            2.000000        4.000000
max            3.000000        4.000000
(8300, 31)

In [4]:
df.isnull().sum()

EmployeeID                     0
EmployeeName                   0
Age                          985
Gender                         0
Department                   940
JobRole                      849
EducationField                 0
Education                      0
MonthlyIncome                774
HourlyRate                     0
DailyRate                      0
YearsAtCompany               592
YearsInCurrentRole             0
YearsWithCurrManager           0
TotalWorkingYears           1112
NumCompaniesWorked             0
JobSatisfaction              992
EnvironmentSatisfaction        0
WorkLifeBalance              891
PerformanceRating            580
RelationshipSatisfaction       0
BusinessTravel                 0
MaritalStatus                  0
DistanceFromHome               0
OverTime                     605
PercentSalaryHike              0
TrainingTimesLastYear          0
StockOptionLevel               0
JobInvolvement                 0
Attrition                      0
JoiningDate                 1790
dtype: int64

In [5]:
df = df.dropna()

In [6]:
df.isnull().sum()

EmployeeID                  0
EmployeeName                0
Age                         0
Gender                      0
Department                  0
JobRole                     0
EducationField              0
Education                   0
MonthlyIncome               0
HourlyRate                  0
DailyRate                   0
YearsAtCompany              0
YearsInCurrentRole          0
YearsWithCurrManager        0
TotalWorkingYears           0
NumCompaniesWorked          0
JobSatisfaction             0
EnvironmentSatisfaction     0
WorkLifeBalance             0
PerformanceRating           0
RelationshipSatisfaction    0
BusinessTravel              0
MaritalStatus               0
DistanceFromHome            0
OverTime                    0
PercentSalaryHike           0
TrainingTimesLastYear       0
StockOptionLevel            0
JobInvolvement              0
Attrition                   0
JoiningDate                 0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(2)

In [8]:
df = df.drop_duplicates()

In [9]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.dtypes

employeeid                      str
employeename                    str
age                             str
gender                          str
department                      str
jobrole                         str
educationfield                  str
education                     int64
monthlyincome                   str
hourlyrate                    int64
dailyrate                     int64
yearsatcompany              float64
yearsincurrentrole            int64
yearswithcurrmanager          int64
totalworkingyears           float64
numcompaniesworked            int64
jobsatisfaction             float64
environmentsatisfaction       int64
worklifebalance             float64
performancerating           float64
relationshipsatisfaction      int64
businesstravel                  str
maritalstatus                   str
distancefromhome              int64
overtime                        str
percentsalaryhike             int64
trainingtimeslastyear         int64
stockoptionlevel              int64
jobinvolvement                int64
attrition                       str
joiningdate                     str
dtype: object

In [14]:
df["department"].unique()

<StringArray>
[                      'it',                      'R&D',
               'Operations',          'Human resources',
                       'IT',                    'Sales',
                  'Finance',               'sales dept',
                'Marketing',                  'IT dept',
   'Research & Development',          'Human Resources',
          'human resources',                   'Sales ',
                    'R & D',  'Research & Development ',
 'research and development',                 'Finance ',
                    'SALES',                       'HR',
                    'sales',                      'H.R']
Length: 22, dtype: str

In [15]:
df["department"] = df["department"].str.title()

In [16]:
df["department"].unique()

<StringArray>
[                      'It',                      'R&D',
               'Operations',          'Human Resources',
                    'Sales',                  'Finance',
               'Sales Dept',                'Marketing',
                  'It Dept',   'Research & Development',
                   'Sales ',                    'R & D',
  'Research & Development ', 'Research And Development',
                 'Finance ',                       'Hr',
                      'H.R']
Length: 17, dtype: str

In [18]:
print(df.shape)
print(df.isnull().sum())
print(df.duplicated().sum())
print(df.info())

(2281, 31)
employeeid                  0
employeename                0
age                         0
gender                      0
department                  0
jobrole                     0
educationfield              0
education                   0
monthlyincome               0
hourlyrate                  0
dailyrate                   0
yearsatcompany              0
yearsincurrentrole          0
yearswithcurrmanager        0
totalworkingyears           0
numcompaniesworked          0
jobsatisfaction             0
environmentsatisfaction     0
worklifebalance             0
performancerating           0
relationshipsatisfaction    0
businesstravel              0
maritalstatus               0
distancefromhome            0
overtime                    0
percentsalaryhike           0
trainingtimeslastyear       0
stockoptionlevel            0
jobinvolvement              0
attrition                   0
joiningdate                 0
dtype: int64
0
<class 'pandas.DataFrame'>
Index: 2281 entries, 6 to 8298
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   employeeid                2281 non-null   str
 1   employeename              2281 non-null   str
 2   age                       2281 non-null   str
 3   gender                    2281 non-null   str
 4   department                2281 non-null   str
 5   jobrole                   2281 non-null   str
 6   educationfield            2281 non-null   str
 7   education                 2281 non-null   int64
 8   monthlyincome             2281 non-null   str
 9   hourlyrate                2281 non-null   int64
 10  dailyrate                 2281 non-null   int64
 11  yearsatcompany            2281 non-null   float64
 12  yearsincurrentrole        2281 non-null   int64
 13  yearswithcurrmanager      2281 non-null   int64
 14  totalworkingyears         2281 non-null   float64
 15  numcompaniesworked        2281 non-null   int64
 16  jobsatisfaction           2281 non-null   float64
 17  environmentsatisfaction   2281 non-null   int64
 18  worklifebalance           2281 non-null   float64
 19  performancerating         2281 non-null   float64
 20  relationshipsatisfaction  2281 non-null   int64
 21  businesstravel            2281 non-null   str
 22  maritalstatus             2281 non-null   str
 23  distancefromhome          2281 non-null   int64
 24  overtime                  2281 non-null   str
 25  percentsalaryhike         2281 non-null   int64
 26  trainingtimeslastyear     2281 non-null   int64
 27  stockoptionlevel          2281 non-null   int64
 28  jobinvolvement            2281 non-null   int64
 29  attrition                 2281 non-null   str
 30  joiningdate               2281 non-null   str
dtypes: float64(5), int64(13), str(13)
memory usage: 570.2 KB
None

In [19]:
print(df.head())
print(df.info())
print(df.describe())
print(df.shape)

   employeeid        employeename   age  gender       department  \
6     EMP5849         James Jones  39.0  fEmale               It
9     EMP6499         Nancy Davis  22.0    MALE              R&D
10    EMP7522    Anthony White     27.0  Female       Operations
23    EMP3199         Betty Jones  31.0    Male  Human Resources
31    EMP8321       William Brown  57.0  Female               It

                  jobrole    educationfield  education monthlyincome  \
6   Laboratory Technician  Technical Degree          3       15705.0
9         Operations Lead   Human Resources          2       19011.0
10      Financial Analyst         Marketing          5       13027.0
23      HR Representative         Marketing          4       18321.0
31      HR Representative           Medical          1       13531.0

    hourlyrate  ...     businesstravel  maritalstatus  distancefromhome  \
6           58  ...  Travel_Frequently       Divorced                25
9           59  ...      Travel_Rarely         Single                12
10          81  ...         Non-Travel         Single                 9
23          80  ...  Travel_Frequently        Married                 3
31          75  ...  Travel_Frequently       Divorced                15

    overtime  percentsalaryhike  trainingtimeslastyear  stockoptionlevel  \
6         No                 16                      1                 0
9        Yes                 19                      6                 1
10       Yes                 22                      2                 0
23         0                 15                      6                 3
31       Yes                 18                      1                 0

    jobinvolvement  attrition  joiningdate
6                4        Yes    1-10-2010
9                4         No   2016-01-12
10               3        yes    22-7-2019
23               4          Y  14 May 2021
31               2          1  13 Oct 2012

[5 rows x 31 columns]
<class 'pandas.DataFrame'>
Index: 2281 entries, 6 to 8298
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   employeeid                2281 non-null   str
 1   employeename              2281 non-null   str
 2   age                       2281 non-null   str
 3   gender                    2281 non-null   str
 4   department                2281 non-null   str
 5   jobrole                   2281 non-null   str
 6   educationfield            2281 non-null   str
 7   education                 2281 non-null   int64
 8   monthlyincome             2281 non-null   str
 9   hourlyrate                2281 non-null   int64
 10  dailyrate                 2281 non-null   int64
 11  yearsatcompany            2281 non-null   float64
 12  yearsincurrentrole        2281 non-null   int64
 13  yearswithcurrmanager      2281 non-null   int64
 14  totalworkingyears         2281 non-null   float64
 15  numcompaniesworked        2281 non-null   int64
 16  jobsatisfaction           2281 non-null   float64
 17  environmentsatisfaction   2281 non-null   int64
 18  worklifebalance           2281 non-null   float64
 19  performancerating         2281 non-null   float64
 20  relationshipsatisfaction  2281 non-null   int64
 21  businesstravel            2281 non-null   str
 22  maritalstatus             2281 non-null   str
 23  distancefromhome          2281 non-null   int64
 24  overtime                  2281 non-null   str
 25  percentsalaryhike         2281 non-null   int64
 26  trainingtimeslastyear     2281 non-null   int64
 27  stockoptionlevel          2281 non-null   int64
 28  jobinvolvement            2281 non-null   int64
 29  attrition                 2281 non-null   str
 30  joiningdate               2281 non-null   str
dtypes: float64(5), int64(13), str(13)
memory usage: 570.2 KB
None
         education   hourlyrate    dailyrate  yearsatcompany  \
count  2281.000000  2281.000000  2281.000000     2281.000000
mean      3.011399    64.574748   753.029811       19.217010
std       1.400768    20.446652   378.657250       43.195413
min       1.000000    30.000000   100.000000       -3.000000
25%       2.000000    47.000000   415.000000        8.000000
50%       3.000000    65.000000   765.000000       17.000000
75%       4.000000    82.000000  1069.000000       26.000000
max       5.000000   100.000000  1400.000000      999.000000

       yearsincurrentrole  yearswithcurrmanager  totalworkingyears  \
count         2281.000000           2281.000000        2281.000000
mean             6.875932              6.641385          19.519071
std              5.313500              5.111505          11.667495
min              0.000000              0.000000           0.000000
25%              2.000000              2.000000          10.000000
50%              6.000000              6.000000          19.000000
75%             11.000000             11.000000          30.000000
max             18.000000             17.000000          40.000000

       numcompaniesworked  jobsatisfaction  environmentsatisfaction  \
count         2281.000000      2281.000000              2281.000000
mean             4.437966         2.530031                 2.501973
std              2.872394         1.099879                 1.122388
min              0.000000         1.000000                 1.000000
25%              2.000000         2.000000                 1.000000
50%              4.000000         3.000000                 2.000000
75%              7.000000         3.000000                 4.000000
max              9.000000         4.000000                 4.000000

       worklifebalance  performancerating  relationshipsatisfaction  \
count      2281.000000        2281.000000               2281.000000
mean          2.510302           3.137659                  2.450241
std           1.107789           0.344617                  1.105926
min           1.000000           3.000000                  1.000000
25%           2.000000           3.000000                  1.000000
50%           2.000000           3.000000                  2.000000
75%           3.000000           3.000000                  3.000000
max           4.000000           4.000000                  4.000000

       distancefromhome  percentsalaryhike  trainingtimeslastyear  \
count       2281.000000        2281.000000            2281.000000
mean          15.453748          18.128452               2.966681
std            8.595219           4.331310               1.995551
min            1.000000          11.000000               0.000000
25%            8.000000          14.000000               1.000000
50%           16.000000          18.000000               3.000000
75%           23.000000          22.000000               5.000000
max           30.000000          25.000000               6.000000

       stockoptionlevel  jobinvolvement
count       2281.000000     2281.000000
mean           1.517317        2.523016
std            1.126547        1.120589
min            0.000000        1.000000
25%            1.000000        2.000000
50%            2.000000        3.000000
75%            3.000000        4.000000
max            3.000000        4.000000
(2281, 31)

In [21]:
# Standardize text
df["gender"] = df["gender"].str.strip().str.lower()

# Replace variations
df["gender"] = df["gender"].replace({
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female"
})

In [22]:
print(df.head())
print(df.info())
print(df.describe())
print(df.shape)

   employeeid        employeename   age  gender       department  \
6     EMP5849         James Jones  39.0  Female               It
9     EMP6499         Nancy Davis  22.0    Male              R&D
10    EMP7522    Anthony White     27.0  Female       Operations
23    EMP3199         Betty Jones  31.0    Male  Human Resources
31    EMP8321       William Brown  57.0  Female               It

                  jobrole    educationfield  education monthlyincome  \
6   Laboratory Technician  Technical Degree          3       15705.0
9         Operations Lead   Human Resources          2       19011.0
10      Financial Analyst         Marketing          5       13027.0
23      HR Representative         Marketing          4       18321.0
31      HR Representative           Medical          1       13531.0

    hourlyrate  ...     businesstravel  maritalstatus  distancefromhome  \
6           58  ...  Travel_Frequently       Divorced                25
9           59  ...      Travel_Rarely         Single                12
10          81  ...         Non-Travel         Single                 9
23          80  ...  Travel_Frequently        Married                 3
31          75  ...  Travel_Frequently       Divorced                15

    overtime  percentsalaryhike  trainingtimeslastyear  stockoptionlevel  \
6         No                 16                      1                 0
9        Yes                 19                      6                 1
10       Yes                 22                      2                 0
23         0                 15                      6                 3
31       Yes                 18                      1                 0

    jobinvolvement  attrition  joiningdate
6                4        Yes    1-10-2010
9                4         No   2016-01-12
10               3        yes    22-7-2019
23               4          Y  14 May 2021
31               2          1  13 Oct 2012

[5 rows x 31 columns]
<class 'pandas.DataFrame'>
Index: 2281 entries, 6 to 8298
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   employeeid                2281 non-null   str
 1   employeename              2281 non-null   str
 2   age                       2281 non-null   str
 3   gender                    2281 non-null   str
 4   department                2281 non-null   str
 5   jobrole                   2281 non-null   str
 6   educationfield            2281 non-null   str
 7   education                 2281 non-null   int64
 8   monthlyincome             2281 non-null   str
 9   hourlyrate                2281 non-null   int64
 10  dailyrate                 2281 non-null   int64
 11  yearsatcompany            2281 non-null   float64
 12  yearsincurrentrole        2281 non-null   int64
 13  yearswithcurrmanager      2281 non-null   int64
 14  totalworkingyears         2281 non-null   float64
 15  numcompaniesworked        2281 non-null   int64
 16  jobsatisfaction           2281 non-null   float64
 17  environmentsatisfaction   2281 non-null   int64
 18  worklifebalance           2281 non-null   float64
 19  performancerating         2281 non-null   float64
 20  relationshipsatisfaction  2281 non-null   int64
 21  businesstravel            2281 non-null   str
 22  maritalstatus             2281 non-null   str
 23  distancefromhome          2281 non-null   int64
 24  overtime                  2281 non-null   str
 25  percentsalaryhike         2281 non-null   int64
 26  trainingtimeslastyear     2281 non-null   int64
 27  stockoptionlevel          2281 non-null   int64
 28  jobinvolvement            2281 non-null   int64
 29  attrition                 2281 non-null   str
 30  joiningdate               2281 non-null   str
dtypes: float64(5), int64(13), str(13)
memory usage: 570.2 KB
None
         education   hourlyrate    dailyrate  yearsatcompany  \
count  2281.000000  2281.000000  2281.000000     2281.000000
mean      3.011399    64.574748   753.029811       19.217010
std       1.400768    20.446652   378.657250       43.195413
min       1.000000    30.000000   100.000000       -3.000000
25%       2.000000    47.000000   415.000000        8.000000
50%       3.000000    65.000000   765.000000       17.000000
75%       4.000000    82.000000  1069.000000       26.000000
max       5.000000   100.000000  1400.000000      999.000000

       yearsincurrentrole  yearswithcurrmanager  totalworkingyears  \
count         2281.000000           2281.000000        2281.000000
mean             6.875932              6.641385          19.519071
std              5.313500              5.111505          11.667495
min              0.000000              0.000000           0.000000
25%              2.000000              2.000000          10.000000
50%              6.000000              6.000000          19.000000
75%             11.000000             11.000000          30.000000
max             18.000000             17.000000          40.000000

       numcompaniesworked  jobsatisfaction  environmentsatisfaction  \
count         2281.000000      2281.000000              2281.000000
mean             4.437966         2.530031                 2.501973
std              2.872394         1.099879                 1.122388
min              0.000000         1.000000                 1.000000
25%              2.000000         2.000000                 1.000000
50%              4.000000         3.000000                 2.000000
75%              7.000000         3.000000                 4.000000
max              9.000000         4.000000                 4.000000

       worklifebalance  performancerating  relationshipsatisfaction  \
count      2281.000000        2281.000000               2281.000000
mean          2.510302           3.137659                  2.450241
std           1.107789           0.344617                  1.105926
min           1.000000           3.000000                  1.000000
25%           2.000000           3.000000                  1.000000
50%           2.000000           3.000000                  2.000000
75%           3.000000           3.000000                  3.000000
max           4.000000           4.000000                  4.000000

       distancefromhome  percentsalaryhike  trainingtimeslastyear  \
count       2281.000000        2281.000000            2281.000000
mean          15.453748          18.128452               2.966681
std            8.595219           4.331310               1.995551
min            1.000000          11.000000               0.000000
25%            8.000000          14.000000               1.000000
50%           16.000000          18.000000               3.000000
75%           23.000000          22.000000               5.000000
max           30.000000          25.000000               6.000000

       stockoptionlevel  jobinvolvement
count       2281.000000     2281.000000
mean           1.517317        2.523016
std            1.126547        1.120589
min            0.000000        1.000000
25%            1.000000        2.000000
50%            2.000000        3.000000
75%            3.000000        4.000000
max            3.000000        4.000000
(2281, 31)

In [26]:
df["attrition"] = df["attrition"].str.strip().str.title()

# Check unique values
print(df["attrition"].unique())

<StringArray>
['Yes', 'No', 'Y', '1', 'N', '0']
Length: 6, dtype: str

In [27]:
df["attrition"] = df["attrition"].replace({
    "Y": "Yes",
    "N": "No",
    "YES": "Yes",
    "NO": "No"
})

In [32]:
print(df.columns.tolist())

['employeeid', 'employeename', 'age', 'gender', 'department', 'jobrole', 'educationfield', 'education', 'monthlyincome', 'hourlyrate', 'dailyrate', 'yearsatcompany', 'yearsincurrentrole', 'yearswithcurrmanager', 'totalworkingyears', 'numcompaniesworked', 'jobsatisfaction', 'environmentsatisfaction', 'worklifebalance', 'performancerating', 'relationshipsatisfaction', 'businesstravel', 'maritalstatus', 'distancefromhome', 'overtime', 'percentsalaryhike', 'trainingtimeslastyear', 'stockoptionlevel', 'jobinvolvement', 'attrition', 'joiningdate']

In [33]:
df.columns = [
    'EmployeeID',
    'EmployeeName',
    'Age',
    'Gender',
    'Department',
    'JobRole',
    'EducationField',
    'Education',
    'MonthlyIncome',
    'HourlyRate',
    'DailyRate',
    'YearsAtCompany',
    'YearsInCurrentRole',
    'YearsWithCurrentManager',
    'TotalWorkingYears',
    'NumCompaniesWorked',
    'JobSatisfaction',
    'EnvironmentSatisfaction',
    'WorkLifeBalance',
    'PerformanceRating',
    'RelationshipSatisfaction',
    'BusinessTravel',
    'MaritalStatus',
    'DistanceFromHome',
    'OverTime',
    'PercentSalaryHike',
    'TrainingTimesLastYear',
    'StockOptionLevel',
    'JobInvolvement',
    'Attrition',
    'JoiningDate'
]

In [34]:
print(df.columns.tolist())

['EmployeeID', 'EmployeeName', 'Age', 'Gender', 'Department', 'JobRole', 'EducationField', 'Education', 'MonthlyIncome', 'HourlyRate', 'DailyRate', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsWithCurrentManager', 'TotalWorkingYears', 'NumCompaniesWorked', 'JobSatisfaction', 'EnvironmentSatisfaction', 'WorkLifeBalance', 'PerformanceRating', 'RelationshipSatisfaction', 'BusinessTravel', 'MaritalStatus', 'DistanceFromHome', 'OverTime', 'PercentSalaryHike', 'TrainingTimesLastYear', 'StockOptionLevel', 'JobInvolvement', 'Attrition', 'JoiningDate']

In [37]:
df["JoiningDate"] = pd.to_datetime(df["JoiningDate"], errors="coerce")

In [38]:
print(df["JoiningDate"].dtype)

datetime64[us]

In [39]:
df["JoiningDate"] = pd.to_datetime(
    df["JoiningDate"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [40]:
print(df["JoiningDate"].isna().sum())

2128

In [41]:
df["JoiningDate"] = pd.to_datetime(df["JoiningDate"], errors="coerce")

df["JoinYear"] = df["JoiningDate"].dt.year
df["JoinMonth"] = df["JoiningDate"].dt.month_name()
df["JoinQuarter"] = df["JoiningDate"].dt.quarter

In [42]:
print(df["JoiningDate"].head())

6    2010-01-10
9           NaT
10          NaT
23          NaT
31          NaT
Name: JoiningDate, dtype: datetime64[us]

In [43]:
df.loc[df["JoiningDate"].isna(), ["JoiningDate"]]

     JoiningDate
9            NaT
10           NaT
23           NaT
31           NaT
33           NaT
...          ...
8285         NaT
8287         NaT
8294         NaT
8297         NaT
8298         NaT

[2128 rows x 1 columns]

In [44]:
df[df["JoiningDate"].isna()]

,EmployeeID,EmployeeName,Age,Gender,Department,JobRole,EducationField,Education,MonthlyIncome,HourlyRate,...,OverTime,PercentSalaryHike,TrainingTimesLastYear,StockOptionLevel,JobInvolvement,Attrition,JoiningDate,JoinYear,JoinMonth,JoinQuarter
9,EMP6499,Nancy Davis,22.0,Male,R&D,Operations Lead,Human Resources,2,19011.0,59,...,Yes,19,6,1,4,No,NaT,NaN,NaN,NaN
10,EMP7522,Anthony White,27.0,Female,Operations,Financial Analyst,Marketing,5,13027.0,81,...,Yes,22,2,0,3,Yes,NaT,NaN,NaN,NaN
23,EMP3199,Betty Jones,31.0,Male,Human Resources,HR Representative,Marketing,4,18321.0,80,...,0,15,6,3,4,Yes,NaT,NaN,NaN,NaN
31,EMP8321,William Brown,57.0,Female,It,HR Representative,Medical,1,13531.0,75,...,Yes,18,1,0,2,1,NaT,NaN,NaN,NaN
33,EMP1459,Michael Garcia,35.0,Male,It,Financial Analyst,Other,3,10871.0,72,...,0,15,1,1,4,No,NaT,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8285,EMP8680,Richard Thompson,54.0,Male,Sales,Research Scientist,Human Resources,1,19033.0,93,...,No,19,4,0,4,No,NaT,NaN,NaN,NaN
8287,EMP7015,John Allen,38.0,Female,Human Resources,Sales Executive,Human Resources,3,17556.0,72,...,Yes,16,5,3,3,No,NaT,NaN,NaN,NaN
8294,EMP8566,Linda Williams,35.0,Male,It,Sales Executive,Marketing,4,5044.0,32,...,Yes,21,3,0,2,No,NaT,NaN,NaN,NaN
8297,EMP5307,Lisa Brown,52.0,Female,Marketing,Financial Analyst,Other,5,5377.0,80,...,No,20,0,2,2,Yes,NaT,NaN,NaN,NaN
8298,EMP6699,Margaret Johnson,46.0,Female,Operations,Software Engineer,Life Sciences,3,8748.0,80,...,Yes,22,0,2,3,No,NaT,NaN,NaN,NaN

In [45]:
print(df["JoiningDate"].unique())

<DatetimeArray>
['2010-01-10 00:00:00',                 'NaT', '2015-03-05 00:00:00',
 '2013-11-01 00:00:00', '2017-03-09 00:00:00', '2021-01-09 00:00:00',
 '2024-06-06 00:00:00', '2020-12-09 00:00:00', '2024-01-12 00:00:00',
 '2017-05-10 00:00:00',
 ...
 '2016-07-10 00:00:00', '2012-07-07 00:00:00', '2021-10-08 00:00:00',
 '2011-04-11 00:00:00', '2019-07-09 00:00:00', '2016-05-07 00:00:00',
 '2022-08-04 00:00:00', '2011-03-10 00:00:00', '2015-02-06 00:00:00',
 '2022-12-05 00:00:00']
Length: 146, dtype: datetime64[us]

In [46]:
df["JoiningDate"] = pd.to_datetime(
    df["JoiningDate"],
    errors="coerce",
    dayfirst=True
)

In [47]:
print(df["JoiningDate"].isna().sum())

2128

In [48]:
invalid_dates = df.loc[df["JoiningDate"].isna()]
print(invalid_dates)

     EmployeeID           EmployeeName   Age  Gender       Department  \
9       EMP6499            Nancy Davis  22.0    Male              R&D
10      EMP7522       Anthony White     27.0  Female       Operations
23      EMP3199            Betty Jones  31.0    Male  Human Resources
31      EMP8321          William Brown  57.0  Female               It
33      EMP1459         Michael Garcia  35.0    Male               It
...         ...                    ...   ...     ...              ...
8285    EMP8680       Richard Thompson  54.0    Male            Sales
8287    EMP7015             John Allen  38.0  Female  Human Resources
8294    EMP8566         Linda Williams  35.0    Male               It
8297    EMP5307             Lisa Brown  52.0  Female        Marketing
8298    EMP6699    Margaret Johnson     46.0  Female       Operations

                 JobRole   EducationField  Education MonthlyIncome  \
9        Operations Lead  Human Resources          2       19011.0
10     Financial Analyst        Marketing          5       13027.0
23     HR Representative        Marketing          4       18321.0
31     HR Representative          Medical          1       13531.0
33     Financial Analyst            Other          3       10871.0
...                  ...              ...        ...           ...
8285  Research Scientist  Human Resources          1       19033.0
8287     Sales Executive  Human Resources          3       17556.0
8294     Sales Executive        Marketing          4        5044.0
8297   Financial Analyst            Other          5        5377.0
8298   Software Engineer    Life Sciences          3        8748.0

      HourlyRate  ...  OverTime  PercentSalaryHike  TrainingTimesLastYear  \
9             59  ...       Yes                 19                      6
10            81  ...       Yes                 22                      2
23            80  ...         0                 15                      6
31            75  ...       Yes                 18                      1
33            72  ...         0                 15                      1
...          ...  ...       ...                ...                    ...
8285          93  ...        No                 19                      4
8287          72  ...       Yes                 16                      5
8294          32  ...       Yes                 21                      3
8297          80  ...        No                 20                      0
8298          80  ...       Yes                 22                      0

      StockOptionLevel  JobInvolvement  Attrition  JoiningDate  JoinYear  \
9                    1               4         No          NaT       NaN
10                   0               3        Yes          NaT       NaN
23                   3               4        Yes          NaT       NaN
31                   0               2          1          NaT       NaN
33                   1               4         No          NaT       NaN
...                ...             ...        ...          ...       ...
8285                 0               4         No          NaT       NaN
8287                 3               3         No          NaT       NaN
8294                 0               2         No          NaT       NaN
8297                 2               2        Yes          NaT       NaN
8298                 2               3         No          NaT       NaN

      JoinMonth  JoinQuarter
9           NaN          NaN
10          NaN          NaN
23          NaN          NaN
31          NaN          NaN
33          NaN          NaN
...         ...          ...
8285        NaN          NaN
8287        NaN          NaN
8294        NaN          NaN
8297        NaN          NaN
8298        NaN          NaN

[2128 rows x 34 columns]

In [49]:
print(df.loc[df["JoiningDate"].isna(), "JoiningDate"])

9      NaT
10     NaT
23     NaT
31     NaT
33     NaT
        ..
8285   NaT
8287   NaT
8294   NaT
8297   NaT
8298   NaT
Name: JoiningDate, Length: 2128, dtype: datetime64[us]

In [50]:
# Show all rows
pd.set_option('display.max_rows', None)

# Show all columns
pd.set_option('display.max_columns', None)

# Show full column width
pd.set_option('display.max_colwidth', None)

# Display entire DataFrame
print(df)

     EmployeeID            EmployeeName          Age  Gender  \
6       EMP5849             James Jones         39.0  Female
9       EMP6499             Nancy Davis         22.0    Male
10      EMP7522        Anthony White            27.0  Female
23      EMP3199             Betty Jones         31.0    Male
31      EMP8321           William Brown         57.0  Female
33      EMP1459          Michael Garcia         35.0    Male
41      EMP5984          Patricia Jones         35.0  Female
45      EMP1445    Christopher Williams         55.0    Male
46      EMP6147            Sarah Thomas         59.0  Female
47      EMP8836          Anthony Garcia         56.0  Female
48      EMP5768         Anthony Jackson         42.0  Female
49      EMP6592            Robert Moore         45.0    Male
50      EMP7020           Richard Davis         29.0    Male
52      EMP4739           William Young         58.0    Male
54      EMP8227           Betty Johnson      unknown    Male
56      EMP5549             Mary Taylor         51.0    Male
58      EMP7136         Michael Johnson         54.0  Female
59      EMP7724            Sarah Garcia         22.0  Female
60      EMP2740           Anthony Young         25.0    Male
62      EMP5300            Robert Davis         46.0  Female
70      EMP6971            Thomas Allen         40.0    Male
72      EMP1112           Michael White         34.0  Female
78      EMP3950          Charles Martin         54.0  Female
79      EMP1094           Richard Moore         36.0  Female
80      EMP1387           Daniel Thomas         33.0  Female
82      EMP1275          Margaret Jones         59.0  Female
85      EMP1727           Robert Harris         18.0  Female
86      EMP2881            Karen Garcia         60.0    Male
88      EMP7454      Anthony Anderson??         51.0    Male
93      EMP5298         Joseph Thompson         44.0  Female
95      EMP8211          Michael Garcia         33.0  Female
110     EMP4503       Margaret Anderson         44.0  Female
114     EMP5740         Margaret Taylor         20.0    Male
117     EMP4571            Ashley Moore         44.0  Female
118     EMP4950           Nancy Johnson         24.0  Female
121     EMP3039           John Thompson         35.0    Male
129     EMP6726          Jessica Taylor         42.0  Female
130     EMP8103            Ashley Allen         22.0    Male
134     EMP3350            David Garcia         51.0    Male
136     EMP3411            Sarah Garcia         55.0  Female
140     EMP8157           Jessica Allen         18.0    Male
141     EMP4706             Karen Davis         36.0    Male
152     EMP6876             John Thomas         47.0  Female
157     EMP6780            Linda Wilson         21.0  Female
159     EMP1950            Karen Wilson         56.0  Female
160     EMP5823             Sarah Allen         32.0    Male
165     EMP2285          Richard Wilson         53.0    Male
170     EMP2763             Nancy Jones         42.0    Male
171     EMP5283      Jennifer Harris            19.0    Male
177     EMP6599              John Smith         56.0    Male
179     EMP1797          Karen White            41.0  Female
187     EMP5078          Margaret Allen         57.0    Male
188     EMP2858            Daniel Moore         53.0  Female
190     EMP1140            Betty Garcia         53.0  Female
194     EMP1901          Patricia Davis         20.0  Female
198     EMP8171           Thomas Taylor         23.0  Female
203     EMP5457          Susan Anderson         48.0    Male
206     EMP8460        Jessica Thompson         29.0  Female
211     EMP6684           Joseph Miller         20.0    Male
213     EMP3397          Nancy Thompson         18.0    Male
214     EMP3099        Barbara Anderson         53.0    Male
215     EMP1158             David Davis         50.0    Male
217     EMP2871          Jennifer White         31.0    Male
218     EMP2145           Jessica Brown         24.0  Female
222     EMP5154        Ashley Taylor            31.0  Female
231     EMP3638         Patricia Taylor         59.0  Female
232     EMP4438            Nancy Martin         18.0  Female
235     EMP8734             David Davis         46.0  Female
236     EMP5401          Sandra Jackson         40.0    Male
237     EMP4834          Michael Thomas         56.0    Male
239     EMP8125            Betty Wilson         23.0    Male
243     EMP2734         James Miller            44.0  Female
247     EMP4813          Sandra Jackson         47.0  Female
248     EMP1885            Joseph Allen         30.0  Female
251     EMP4611          Joseph Jackson         54.0    Male
252     EMP2568          Ashley Jackson         47.0    Male
253     EMP6524            Sarah Miller         18.0    Male
254     EMP5913            Ashley Davis         48.0    Male
266     EMP1896     Christopher Jackson         46.0  Female
273     EMP4405          Daniel Jackson         54.0    Male
274     EMP4063            Susan Taylor         52.0  Female
275     EMP7457            Ashley Jones         34.0  Female
276     EMP8886           Daniel Martin         27.0  Female
279     EMP1965           Daniel Taylor         19.0  Female
286     EMP4865        Charles Anderson         33.0    Male
290     EMP2279        William Williams         49.0    Male
294     EMP8020            Nancy Thomas         34.0  Female
295     EMP5592         Jessica Johnson         42.0  Female
296     EMP2802            Thomas Jones         46.0  Female
299     EMP2696           Matthew White         40.0    Male
300     EMP3132            Joseph Smith         25.0    Male
304     EMP3976          David Thompson         33.0    Male
306     EMP3532              Mark Davis         60.0  Female
311     EMP3625             Mark Miller         50.0  Female
312     EMP6872             Nancy Davis         57.0  Female
314     EMP1540         Richard Jackson         36.0  Female
315     EMP1479             Betty Allen         25.0  Female
316     EMP1420      Christopher Taylor         50.0  Female
324     EMP7421         Margaret Miller         60.0    Male
326     EMP5830           Richard Smith         58.0    Male
330     EMP5698         Margaret Miller         24.0  Female
337     EMP3593            David Martin         36.0  Female
338     EMP4547             Nancy Allen         18.0  Female
348     EMP1460          Karen Jones            53.0  Female
349     EMP2675             John Wilson         39.0  Female
355     EMP2417             Nancy Brown         39.0    Male
358     EMP7655            Betty Wilson         42.0    Male
359     EMP6305           Sandra Martin         60.0  Female
361     EMP8759          Matthew Taylor         42.0  Female
372     EMP6146             Nancy Allen         54.0    Male
379     EMP3644              Lisa Brown         60.0    Male
380     EMP1695        Anthony Williams         51.0  Female
388     EMP4838        Barbara Miller??         29.0    Male
396     EMP7609             Linda Davis         23.0  Female
397     EMP7816          Richard Wilson         20.0  Female
398     EMP4730              Lisa Smith         -5.0    Male
408     EMP1610             Karen Brown         33.0  Female
410     EMP5420             Linda Smith         28.0    Male
411     EMP3768            Betty Thomas         53.0    Male
414     EMP8388          Jennifer White         49.0  Female
415     EMP3021          Patricia Brown         19.0  Female
418     EMP7204      Jennifer Harris            60.0    Male
422     EMP5714    Christopher Anderson         60.0    Male
429     EMP7231      Christopher Wilson         20.0  Female
431     EMP3381           Matthew Brown         37.0    Male
432     EMP6838           Barbara Moore         19.0    Male
434     EMP6115    Christopher Smith            44.0    Male
446     EMP1582         Joseph Thompson         48.0    Male
447     EMP7013          Patricia Davis         48.0  Female
448     EMP3327             James Smith         24.0    Male
449     EMP6066           Matthew Allen         52.0    Male
451     EMP4381       Christopher Allen         53.0    Male
455     EMP3004            James Wilson         45.0    Male
458     EMP4612         Daniel Thompson         26.0  Female
466     EMP8374           Anthony Moore         21.0    Male
468     EMP1295          Nancy Anderson         30.0    Male
473     EMP2078          Daniel Johnson         28.0    Male
477     EMP6526          Margaret White         50.0  Female
480     EMP8646              Mark Young         48.0  Female
486     EMP3982           Jessica Moore         56.0  Female
487     EMP3402          Anthony Harris         25.0  Female
490     EMP5728            Nancy Taylor         50.0  Female
491     EMP3311           Jessica Young         21.0    Male
493     EMP2095          Mark Martin            52.0    Male
494     EMP7167         Margaret Harris         21.0  Female
495     EMP4176             Linda Allen         36.0    Male
497     EMP1892            Karen Garcia         21.0  Female
499     EMP6039         William Jackson         54.0    Male
500     EMP7821         Patricia Garcia         20.0  Female
502     EMP5760           Mary Williams         19.0  Female
506     EMP3452       Christopher Brown         41.0  Female
507     EMP2375           Thomas Harris         34.0  Female
510     EMP3784           Robert Garcia         45.0    Male
513     EMP2057          Jessica Taylor         23.0  Female
515     EMP1134          Betty Wilson$$         22.0  Female
518     EMP7001             Lisa Harris         31.0    Male
520     EMP5310           Matthew Jones         20.0  Female
522     EMP6440      Christopher Taylor         57.0    Male
523     EMP7121            Karen Thomas         21.0    Male
525     EMP1101           Sandra Garcia         56.0    Male
536     EMP8304          Jessica Harris         23.0  Female
539     EMP6296          Charles Taylor         30.0  Female
540     EMP7563            Sarah Martin         25.0    Male
542     EMP1246           Michael Allen         56.0  Female
544     EMP3292        Patricia Jackson         52.0    Male
546     EMP2175           Sarah Smith$$         49.0  Female
548     EMP6376        Lisa Williams            24.0    Male
554     EMP1762              Lisa Davis         49.0  Female
557     EMP2872        William Thompson         23.0  Female
561     EMP7306           Daniel Martin         18.0  Female
563     EMP5628         Margaret Martin         54.0  Female
572     EMP8136            Sarah Martin         23.0    Male
576     EMP3731            Robert Smith           --  Female
581     EMP7351          Matthew Taylor         47.0  Female
584     EMP1433           Richard Young         38.0    Male
585     EMP8621          Richard Taylor         44.0  Female
587     EMP7992             Mary Taylor         47.0  Female
592     EMP7799           Sandra Wilson         42.0  Female
596     EMP5899             Lisa Miller         37.0  Female
602     EMP1718          Barbara Martin         22.0    Male
607     EMP6928              Mark Moore         28.0  Female
609     EMP7181        Thomas Miller            32.0  Female
611     EMP7162       Anthony Wilson            56.0    Male
612     EMP7937              Mark Allen         35.0  Female
615     EMP3277          Robert Jackson         42.0    Male
623     EMP4986         Patricia Taylor         33.0    Male
625     EMP6420        Margaret Jackson         49.0    Male
628     EMP2106             Susan Moore         32.0    Male
630     EMP7214           Richard Smith         58.0    Male
635     EMP4430              Mark White         19.0    Male
637     EMP3993       Susan Anderson            21.0  Female
645     EMP8080            Sarah Harris         56.0  Female
648     EMP8718           Joseph Wilson         60.0  Female
649     EMP8170          Margaret Jones         47.0    Male
654     EMP2682        William Anderson       thirty    Male
656     EMP7115       Jessica Johnson**         52.0    Male
657     EMP1451          William Miller         39.0    Male
665     EMP4915          Matthew Taylor         52.0    Male
672     EMP5072          Nancy Davis            59.0    Male
686     EMP6602          Patricia Brown         31.0  Female
688     EMP1521           Barbara Smith         46.0  Female
692     EMP2940           William Davis         27.0  Female
695     EMP8305             Susan Smith         52.0    Male
699     EMP5144        Barbara Thompson         38.0    Male
701     EMP2657          Jessica Garcia         48.0  Female
703     EMP1835          Robert Jackson         54.0  Female
708     EMP6177         Mary Thompson**       thirty  Female
709     EMP3523             Nancy Jones         33.0    Male
713     EMP7752             Susan Allen         38.0  Female
717     EMP5095            Ashley Smith         58.0  Female
718     EMP3599            Daniel Moore         42.0    Male
720     EMP6415           Anthony White         20.0  Female
723     EMP2136         Daniel Williams         46.0    Male
726     EMP7916             Mary Garcia         57.0  Female
729     EMP7188            Daniel Moore         20.0  Female
731     EMP7848         Lisa Jackson            30.0    Male
743     EMP8393           Matthew Allen         32.0  Female
756     EMP2126        Matthew Thompson         58.0  Female
758     EMP7755       Jennifer Williams         33.0    Male
760     EMP7057              Mark White         20.0  Female
761     EMP1507       Jennifer Williams         32.0    Male
762     EMP2869           Mark Davis            51.0  Female
764     EMP4511        Linda Anderson??         32.0    Male
766     EMP5368           Barbara Moore         39.0    Male
768     EMP5553          James Thompson         39.0  Female
770     EMP3516            Thomas Jones         44.0    Male
773     EMP2487            Ashley Brown         36.0  Female
774     EMP3762          Robert Jackson         47.0    Male
778     EMP6715          Daniel Johnson         47.0    Male
779     EMP6441             Betty White         40.0  Female
791     EMP5905         Robert Anderson           --  Female
796     EMP4717          Richard Thomas         57.0  Female
803     EMP4197         Thomas Anderson         19.0    Male
822     EMP5442          Anthony Martin         33.0    Male
832     EMP2925          Jennifer Allen         30.0    Male
835     EMP8839             Linda Davis         26.0  Female
837     EMP5964            Mark Johnson         20.0  Female
839     EMP7887         Barbara Johnson         49.0    Male
846     EMP7289             Lisa Thomas         18.0  Female
853     EMP5138            Joseph White         22.0    Male
854     EMP6210       Patricia Williams         20.0    Male
856     EMP6157        Matthew Brown            33.0    Male
868     EMP3652             Lisa Taylor         48.0  Female
869     EMP4635         Lisa Johnson            33.0    Male
874     EMP1905              Mary Moore         46.0    Male
876     EMP7726       Patricia Thompson         49.0    Male
877     EMP4170           Thomas Taylor         27.0    Male
878     EMP7205          David Anderson         55.0    Male
882     EMP5351         Margaret Garcia         41.0    Male
885     EMP6367        Charles Thompson         53.0    Male
887     EMP7982            Susan Garcia         35.0    Male
890     EMP5297          Matthew Miller         58.0    Male
891     EMP2391          Jennifer Moore         32.0    Male
893     EMP5579           Sandra Thomas         20.0    Male
895     EMP7666            David Martin         45.0  Female
897     EMP3562          Thomas Jackson         35.0    Male
898     EMP1484             Linda White         35.0  Female
900     EMP8407            Robert Smith         47.0    Male
907     EMP5543           John Williams         28.0  Female
910     EMP1515          Jessica Harris         47.0    Male
914     EMP2083      Christopher Harris         48.0    Male
918     EMP7332           Anthony Brown         43.0  Female
921     EMP6686             Betty Moore         33.0    Male
934     EMP4784            Sarah Garcia         40.0    Male
938     EMP4823            Joseph Smith         60.0  Female
950     EMP6649             Susan Davis         41.0  Female
956     EMP8842         Charles Johnson         43.0  Female
973     EMP7312         Patricia Wilson         52.0  Female
975     EMP6154           Michael Allen         59.0  Female
976     EMP6639         Matthew Jackson         50.0  Female
979     EMP1456            David Wilson         25.0  Female
980     EMP4841             John Martin         54.0    Male
983     EMP3631             Susan Smith         25.0    Male
984     EMP1213          Daniel Johnson         23.0  Female
996     EMP7483           Richard Moore         30.0  Female
999     EMP5945          Anthony Miller         53.0    Male
1003    EMP5101         Margaret Martin         59.0    Male
1004    EMP1701              Mark Smith         38.0  Female
1006    EMP2683             Sarah Smith         33.0  Female
1010    EMP6695           Joseph Wilson         32.0    Male
1013    EMP2766        Charles Williams         26.0    Male
1016    EMP3134        Charles Williams         26.0  Female
1019    EMP5699           Daniel Taylor         26.0    Male
1023    EMP2343             Nancy Brown         32.0    Male
1026    EMP7632           Richard Smith         30.0  Female
1031    EMP6883          Margaret Allen         34.0  Female
1033    EMP8266           Mary Anderson         58.0  Female
1034    EMP6786          Robert Jackson         39.0    Male
1035    EMP3646          Charles Garcia         18.0  Female
1037    EMP4693        Matthew Williams         20.0    Male
1047    EMP4861            Ashley Moore         55.0    Male
1051    EMP6465             Sarah Allen         54.0  Female
1078    EMP7526         Joseph Williams         37.0  Female
1081    EMP6138             James Davis         29.0    Male
1087    EMP8448      Christopher Harris         43.0    Male
1088    EMP4166         Ashley Williams         51.0    Male
1089    EMP6443          Betty Thompson         34.0    Male
1092    EMP2634          Margaret Young         32.0    Male
1095    EMP6679            Karen Miller         42.0    Male
1103    EMP8441           Matthew Jones       thirty  Female
1110    EMP7335             John Taylor         37.0    Male
1122    EMP2324             Nancy Young         58.0    Male
1124    EMP6627            Ashley Young         19.0  Female
1128    EMP5834          Ashley Johnson         46.0  Female
1132    EMP5168           Michael Allen         48.0    Male
1137    EMP2666          William Thomas         58.0    Male
1138    EMP3172       Margaret Thompson         48.0  Female
1142    EMP6188             Karen Brown         60.0    Male
1143    EMP2985           Matthew White         25.0  Female
1144    EMP2642          William Garcia         18.0    Male
1145    EMP1770         Daniel Anderson         32.0    Male
1147    EMP8544          Matthew Taylor         58.0    Male
1149    EMP3686         Patricia Taylor         18.0  Female
1151    EMP3307    Christopher Williams         52.0  Female
1158    EMP2748       William Miller            56.0    Male
1166    EMP8443         Margaret Garcia         21.0    Male
1169    EMP6822      Anthony Johnson            32.0  Female
1176    EMP5824         Susan Miller            24.0  Female
1178    EMP3126          Charles Thomas         38.0    Male
1181    EMP1621              Mary Young         37.0    Male
1184    EMP6276         Ashley Williams         58.0    Male
1193    EMP3940           Mary Anderson         38.0    Male
1194    EMP3820           Michael Allen         20.0    Male
1202    EMP6322            Nancy Wilson         34.0  Female
1208    EMP5378           Matthew Allen         59.0  Female
1209    EMP6825        John Anderson            26.0    Male

In [51]:
df.to_csv("Clean_hr_attrition_dataset.csv", index=False)